---
title: "Cleaning US Census Data"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries
library(readr)
library(dplyr)
library(tidyr)
```

```{r message=FALSE, warning=FALSE, error=TRUE}
# load CSVs
files <- list.files(pattern = "states_.*csv")
df_list <- lapply(files, read_csv)
us_census <- bind_rows(df_list)
```

```{r error=TRUE}
# inspect data
head(us_census)
print(colnames(us_census))
print(str(us_census))
```

```{r error=TRUE}
# drop X1 column
us_census <- us_census %>%
  select(-X1)
head(us_census)
```

```{r error=TRUE}
# remove % from race columns
us_census <- us_census %>%
  mutate(
    Hispanic = gsub("\\%","", Hispanic),
    White = gsub("\\%","", White),
    Black = gsub("\\%","",Black),
    Native = gsub("\\%","",Native),
    Asian = gsub("\\%","",Asian),
    Pacific = gsub("\\%","",Pacific)
    )
head(us_census)
```

```{r error=TRUE}
# remove $ from Income column
us_census <- us_census %>%
  mutate(Income = gsub("\\$","",Income))
head(us_census)
```

```{r error=TRUE}
# separate GenderPop column
us_census <- us_census %>%
  separate(GenderPop, c("male_pop", "female_pop"), "_")
```

```{r error=TRUE}
# clean male and female population columns
us_census <- us_census %>%
  mutate(
    male_pop = gsub("M", "", male_pop),
    female_pop = gsub("F", "", female_pop)
    )

head(us_census)
```

```{r error=TRUE}
# update column data types
# update values of race columns from percent to decimal
us_census <- us_census %>%
  mutate(
    Hispanic = as.numeric(Hispanic) / 100,
    White = as.numeric(White) / 100,
    Black = as.numeric(Black) / 100,
    Native = as.numeric(Native) / 100,
    Asian = as.numeric(Asian) / 100,
    Pacific = as.numeric(Pacific) / 100,
    Income = as.numeric(Income),
    male_pop = as.numeric(male_pop),
    female_pop = as.numeric(female_pop)
  )
head(us_census)
```

```{r error=TRUE}
# check for duplicate rows
duplicates_table <- us_census %>%
  duplicated() %>%
  table()
duplicates_table
print(duplicates_table[2])
```

```{r error=TRUE}
# remove duplicate rows
us_census <- us_census %>%
  distinct()
```

```{r error=TRUE}
# check for duplicate rows
duplicates_table <- us_census %>%
  duplicated() %>%
  table()
duplicates_table
print(duplicates_table[2])
```

```{r error=TRUE}
# clean data frame
head(us_census, 20)
```
