---
title: "ACLU Child Separations"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries
library(readr)
library(dplyr)
```

```{r error=TRUE}
# load data
aclu <- read_csv("aclu_separations.csv")
```

```{r error=TRUE}
# inspect data
head(aclu)
summary(aclu)
```

```{r error=TRUE}
# select columns
aclu <- aclu %>% select(-addr)
```

```{r error=TRUE}
# view columns
print(colnames(aclu))
```

```{r error=TRUE}
# rename columns
aclu <- aclu %>%
  rename(
    city = program_city,
    state = program_state,
    number_children = n,
    longitude = lon,
    latitude = lat
  )

print(colnames(aclu))
```

```{r error=TRUE}
# add column latitude change
border_latitude <- 25.83
aclu <- aclu %>%
  mutate(lat_change_border = latitude - border_latitude)
  
head(aclu)
```

```{r error=TRUE}
# new data frame further away
further_away <- aclu %>%
  filter(lat_change_border > 15)

further_away <- further_away %>%
  arrange(desc(lat_change_border))

head(further_away)
```

```{r error=TRUE}
# number of children
ordered_by_children <- aclu %>%
  arrange(desc(number_children))

head(ordered_by_children)
```

```{r error=TRUE}
# state analysis
chosen_state = "WA"
chosen_state_separation <- aclu %>%
  filter(state == chosen_state)

chosen_state_separation <- chosen_state_separation %>%
  arrange(desc(number_children))

head(chosen_state_separation)
```