---
title: "Predicting Income with Social Data"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load packages and data
library(ggplot2)
library(dplyr)
library(modelr)
psid <- read.csv("psid_2017.csv")

```

```{r}
# view data structure
str(psid)

# plot age
age_dist <- ggplot(psid, aes(x = age)) + geom_bar()
age_dist

# filter to reasonable age group
psid_clean <- psid %>%
  filter(age >= 18 & age <= 75)

# plot flitered age
age_clean_dist <- ggplot(psid_clean, aes(x = age)) + geom_bar()
age_clean_dist

# plot education
education_boxplot <- ggplot(psid_clean, aes(education_years, education_years)) + geom_boxplot()
education_boxplot

# filter to reasonable education levels
psid_clean <- psid_clean %>%
  filter(education_years >= 5 & education_years <= 25)
education_boxplot <- ggplot(psid_clean, aes(education_years, education_years)) + geom_boxplot()
education_boxplot

# plot income
income_boxplot <- psid_clean %>%
  ggplot(aes(labor_income, labor_income)) + geom_boxplot()
income_boxplot

# view income summary statistics
summary(psid_clean$labor_income)

# plot mean income by age
income_by_age_scatterplot <- psid_clean %>%
  group_by(age) %>%
  summarize(mean_income = mean(labor_income)) %>%
  ggplot(aes(age,mean_income)) + geom_point()
income_by_age_scatterplot

# subset data points into train and test sets
set.seed(123)
sample <- sample(c(TRUE, FALSE), nrow(psid_clean), replace = T, prob = c(0.6,0.4))

# define train and test
train <- psid_clean[sample, ]
test <- psid_clean[!sample, ]

# build model
model <- lm(labor_income ~ education_years, data = train)

# plot against LOESS model
plot <- train %>%
  ggplot(aes(education_years, labor_income)) + geom_point() + geom_smooth(method = "lm") + geom_smooth(se = FALSE, color = "red")
plot

# compute r-squared
r_sq <- summary(model)$r.squared * 100

# uncomment to write out r-squared interpretation
sprintf("Based on a simple linear regression model, we have determined that %s percent of the variation in respondent income can be predicted by a respondent's education level.", r_sq)

# build second model
model_2 <- lm(labor_income ~ education_years + age + gender, data = train)
r_sq_2 <- summary(model_2)$r.squared * 100
# uncomment to write out r-squared interpretation
sprintf("Based on a simple linear regression model, we have determined that %s percent of the variation in respondent income can be predicted by a respondent's education level, age and gender.", r_sq_2)

# plot predictions versus observed
plot2 <- test %>%
  add_predictions(model_2) %>%
  ggplot(aes(age, labor_income)) + geom_point() + geom_line(aes(y = pred), color = "blue")
plot2
# write out model results
summary(model_2)
# extract education coefficent
education_coefficient <- summary(model_2)$coefficients[2]
education_coefficient

# uncomment to write out coefficent interpretation
sprintf("Based on a multiple linear regression model of education, age, and gender, for every additional year of formal education, the average American resident's income increases by $%s.", education_coefficient)
```